### ISSUE TITLE
2nd method

### ISSUE THREAD

**Issue by web2033** [Surbma/surbma-divi-remove-project-cpt#1]
Hi!
I use this simple method:
```
 if ( ! function_exists('et_pb_register_posttypes') ) {
	 function et_pb_register_posttypes() {}
 }
```
Any difference?

**Comment by Surbma** [comment]
Is it working? I don't think so. Your condition is checking the function and if it exists, it does nothing. And this function exists in Divi theme.

**Comment by web2033** [comment]
Yes, it works. "It does nothing" means that it doesn't create projects as Divi does))
Divi uses the same condition (pluggable function) so the creation of CPT doesn't run.

**Comment by Surbma** [comment]
It is working, because this function runs first, so your condition is not necessary. I will think about this solution, but I think, this is not the best way to disable this function.

Thank you for your idea!

**Comment by web2033** [comment]
When used in a child themes' functions.php, then yes, you can simply put

> function et_pb_register_posttypes() {}

but when I moved it to a plugin and tried to activate it, WP throw an error (I use multisite)

> Plugin could not be activated because it triggered a fatal error.
> Fatal error: Cannot redeclare et_pb_register_posttypes() (previously declared in .../wp-content/themes/Divi/includes/builder/core.php:1942) in .../wp-content/plugins/disable-cpt-project-divi.php on line 15

and with wrapper, it activates and works)

> if ( ! function_exists('et_pb_register_posttypes') ) {
> 	 function et_pb_register_posttypes() {}
>  }

so I googled and found your solution and just was curious how other people solved it)
